config/routes.rb
Rails.application.routes.draw do
	root   'static_pages#home'

	get    '/help',    to: 'static_pages#help'
	get    '/about',   to: 'static_pages#about'
	post   '/about',    to: 'static_pages#about'
	get    '/contact', to: 'static_pages#contact'
	post   '/contact', to: 'static_pages#send_email', as: 'email'
	get    '/signup',  to: 'users#new'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :users do
		member do
			get :following, :followers
		end
	end

	resources :posts,          only: [:create, :destroy]
	resources :relationships,       only: [:create, :destroy]
	resources :account_activations, only: [:edit]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	scope module: :v1, constraints: ApiVersion.new('1.0') do
		resources :solar_systems, only: :index, path: "solarsystem"

	end
	scope module: :v2, constraints: ApiVersion.new('2.0', true) do
		resources :solar_systems, only: :index, path: "solarsystem"
		resources :solar_systems, only: :index, path: "mercury"
		resources :solar_systems, only: :index, path: "venus"
		resources :solar_systems, only: :index, path: "earth"
		resources :solar_systems, only: :index, path: "mars"
		resources :solar_systems, only: :index, path: "jupiter"
		resources :solar_systems, only: :index, path: "saturn"
		resources :solar_systems, only: :index, path: "uranus"
		resources :solar_systems, only: :index, path: "neptune"
	end


	# post 'auth/login', to: 'authentication#authenticate'
	# post 'auth/signup', to: 'users#create'
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
  format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :posts, dependent: :destroy
  has_many :active_relationships,  class_name:  "Relationship",
  foreign_key: "follower_id",
  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
  foreign_key: "followed_id",
  dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  # Returns the hash digest of the given string.
  #

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end



  def self.search(search)
    where("name ILIKE ? ", "%#{search}%")
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships WHERE  follower_id = #{id}"
    Post.where("user_id IN (#{following_ids})
     OR user_id = #{id}")
  end
  # Follows a user.
  def follow(other_user)
    following << other_user
  end

  # Unfollows a user.
  def unfollow(other_user)
    following.delete(other_user)
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end


  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  # Converts email to all lower-case.
  private
  def downcase_email
    self.email = email.downcase
  end

  # Creates and assigns the activation token and digest.
  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
	before_action :correct_user,   only: [:edit, :update]
	before_action :admin_user,     only: :destroy

	def index
		if params[:search]
			@users = User.search(params[:search]).where(activated: true).order(:name).paginate(page: params[:page], per_page: 5)
		else
			@users = User.where(activated: true).order(:name).paginate(page: params[:page], per_page: 5)
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			auth_token = AuthenticateUser.new(@user.email, @user.password).call
			response = { message: Message.account_created, auth_token: auth_token }
			@user[:api_key] = auth_token

			@user.save

			# json_response(response, :created)
			@user.send_activation_email
			flash[:info] = "Please check your email to activate your account."
			redirect_to root_url

		else
			render 'new'
		end
	end

	def edit
		@user = User.find(params[:id])
	end
	def show
		@user = User.find(params[:id])
		@post  = current_user.posts.build
		@posts = @user.posts.paginate(page: params[:page], per_page: 5)
	end
	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted"
		redirect_to users_url
	end
	def following
		@title = "Following"
		@user  = User.find(params[:id])
		@users = @user.following.order(:name).paginate(page: params[:page])
		render 'show_follow'
	end

	def followers
		@title = "Followers"
		@user  = User.find(params[:id])
		@users = @user.followers.order(:name).paginate(page: params[:page])
		render 'show_follow'
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password,
			:password_confirmation, :term,:api_key)
	end

	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_url) unless current_user?(@user)
	end

	def admin_user
		redirect_to(root_url) unless current_user.admin?
	end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, 'Password Confirmation' %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete},remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>

  <% end %>

</li>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
<h1>Update your profile</h1>
<div class="row">
	<div class="col-md-3">
		<div class="gravatar_edit">
			<%= gravatar_for @user %>
			<a href="http://gravatar.com/emails" target="_blank" style="color:black;">Change</a>
		</div>
		<%= render 'form' %>

	</div>
	<div class="col-md-9">


		<label>Your API_KEY</label>
		<input disabled style="background: #252528 !important;color: #33ff33 !important;" value=<%= @user[:api_key] %>
		<br>
		<hr>
		<label>Sample Request</label>
		<% text = '
var settings = {
  "async": true,
  "crossDomain": true,
  "url": "https://galaxcyclopedia.herokuapp.com/solarsystem/?api_key=' +@user[:api_key] +',
  "method": "GET",
  "headers": {
    "accept": "version.v2.json"
  }
}

$.ajax(settings).done(function (response) {
  console.log(response);
});' %>
		<pre style="overflow:hidden;"><%= text %></pre>
	</div>
</div>

app/views/users/follow.js.erb
<%# app/views/students/index.js.erb %>
<% js = escape_javascript(
  render(partial: 'users/list', locals: { users: @users })
) %>
$("#filterrific_results").html("hi");

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All Users</h1>




<%= form_tag(users_path, :method => "get", id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search By Name:" %>
<%= submit_tag "Search", :name => nil, :class => 'btn-success' %>

<% end %>
<div><%= page_entries_info @users %></div>

<%= will_paginate %>
<hr style="margin-top:-19px;">
<ul class="users">

	<%= render @users %>

</ul>
<% if @users.blank? %>
<h4>There are no users with the name '<%= params[:search] %>'.</h4>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<% provide(:button_text, 'Create my account') %>
<h1 style="color:white">Sign Up</h1>
<div class="homebackground" style="background-image:URL(<%= asset_path('background.png') %>)"></div>

<div class="row" style="color:white">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>

		<%= f.label :email %>
		<%= f.email_field :email, class: 'form-control' %>

		<%= f.label :password %>
		<%= f.password_field :password, class: 'form-control' %>

		<%= f.label :password_confirmation, 'Password Confirmation' %>
		<%= f.password_field :password_confirmation, class: 'form-control' %>

		<%= f.submit yield(:button_text), class: "btn btn-primary hoverbtns" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<%= render 'shared/user_info' %>
		</section>
		<section class="stats">
			<% @user ||= current_user %>
			<div class="stats">
				<a href="<%= following_user_path(@user) %>" style="color:black">
					<strong id="following" class="stat">
						<%= @user.following.count %>
					</strong>
					following
				</a>
				<a href="<%= followers_user_path(@user) %>" style="color:black">
					<strong id="followers" class="stat">
						<%= @user.followers.count %>
					</strong>
					followers
				</a>
			</div>
		</section>


		<section class="post_form">
			<%= render 'shared/post_form' if current_user == @user %>
		</section>



	</aside>
	<div class="col-md-8">
		<%= render 'follow_form' if logged_in? %>

		<% if @user.posts.any? %>
		<h3><%= @user.name %>'s Posts (<%= @user.posts.count %>)</h3>
		<div><%= page_entries_info @posts %></div>
		<div><%= will_paginate @posts %></div>
		<ol class="posts">
			<%= render @posts %>
		</ol>
		<div><%= will_paginate @posts %></div>

		<% end %>
	</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Posts:</b> <%= @user.posts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
      <div class="user_avatars">
        <% @users.each do |user| %>
        <%= link_to gravatar_for(user, size: 30), user %>
        <% end %>
      </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
    <div>
      <%= page_entries_info @users %>
    </div>
    <ul class="users follow">
      <%= render @users %>
    </ul>
    <%= will_paginate %>
    <% end %>
  </div>
</div>