config/routes.rb
Rails.application.routes.draw do
	root   'static_pages#home'

	get    '/help',    to: 'static_pages#help'
	get    '/about',   to: 'static_pages#about'
	post   '/about',    to: 'static_pages#about'
	get    '/contact', to: 'static_pages#contact'
	post   '/contact', to: 'static_pages#send_email', as: 'email'
	get    '/signup',  to: 'users#new'
	get    '/login',   to: 'sessions#new'
	post   '/login',   to: 'sessions#create'
	delete '/logout',  to: 'sessions#destroy'
	resources :users do
		member do
			get :following, :followers
		end
	end

	resources :posts,          only: [:create, :destroy]
	resources :relationships,       only: [:create, :destroy]
	resources :account_activations, only: [:edit]
	resources :password_resets,     only: [:new, :create, :edit, :update]
	scope module: :v1, constraints: ApiVersion.new('1.0') do
		resources :solar_systems, only: :index, path: "solarsystem"

	end
	scope module: :v2, constraints: ApiVersion.new('2.0', true) do
		resources :solar_systems, only: :index, path: "solarsystem"
		resources :solar_systems, only: :index, path: "mercury"
		resources :solar_systems, only: :index, path: "venus"
		resources :solar_systems, only: :index, path: "earth"
		resources :solar_systems, only: :index, path: "mars"
		resources :solar_systems, only: :index, path: "jupiter"
		resources :solar_systems, only: :index, path: "saturn"
		resources :solar_systems, only: :index, path: "uranus"
		resources :solar_systems, only: :index, path: "neptune"
	end


	# post 'auth/login', to: 'authentication#authenticate'
	# post 'auth/signup', to: 'users#create'
end

app/views/layouts/_footer.html.erb
<footer class="footer" style="position:fixed;bottom: 0;left:5vw;width: 90vw;">
  <small>
    Galaxcyclopedia by <a href="https://www.linkedin.com/in/fang-wen-shen/">Fang-Wen Shen</a>
  </small>
  <nav>
    <ul class="" style="color:<%= logged_in? ? 'black' : 'white' %>">
      <li><a href='/contact' style="color:<%= logged_in? ? 'black' : 'white' %>">Contact</a></li>
      <li><a href="https://github.com/fang-w-shen/Galaxcyclopedia" style="color:<%= logged_in? ? 'black' : 'white' %>">Github</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Galaxcyclopedia", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Documentation",   about_path %></li>

        <% if !logged_in? %>
        <li><%= link_to "Sign Up", signup_path %></li>
        <% end %>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#_" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log Out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <meta name="turbolinks-cache-control" content="no-cache">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link href="<%= asset_path('favicon-32x32.png') %>" rel="shortcut icon" type="image/icon" />
  <%= render 'layouts/shim' %>
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <!--<%=  debug(params) if Rails.env.development? %> -->
  </div>
</body>
<% if !logged_in? %>
<script type="text/javascript">
  $('.navbar-inverse').css('background-color', 'rgba(12, 14, 18, 0)')
</script>


<% end %>
<script type="text/javascript">
  switch(window.location.pathname) {
    case '/':

    $($('a[href="/"]')[1]).addClass('highlightednavbar');

    break;
    case '/users':
    $('a[href="/users"]').addClass('highlightednavbar');
    break;
    case '/about':
    $('a[href="/about"]').addClass('highlightednavbar');

    break;
    case '/signup':
    $('a[href="/signup"]').addClass('highlightednavbar');
    break;
    case '/login':
    $('a[href="/login"]').addClass('highlightednavbar');
    break;
    default:
    $('a[href="#_"]').addClass('highlightednavbar');

  }


</script>
</html>